#!/bin/bash
#===============================================================================
#
#          FILE:  maketrans
# 
#         USAGE:  ./maketrans 
# 
#   DESCRIPTION:  用于替换机密字段来生成本地文件
#                 同目录中secret.txt.template文件为密码替换模板
#                 把 secret.txt.template 拷贝成 secret.txt,并根据
#                 实际情况填入相应的值
#                 同目录中file.list文件为替换文件目录
# 
#        AUTHOR:  BaiLiang , bailiangcn@gmail.com
#       COMPANY:  DQYTV
#       VERSION:  1.0
#       CREATED:  2011-03-16 14:24:21
#===============================================================================


#===  FUNCTION  ================================================================
#          NAME:  read_replace_var()
#   DESCRIPTION:  用于构造需要的sed脚本 
#===============================================================================
read_replace_var() {
    echo "开始转换"
    while read x y; do
        str="s/$x/$y/g"
        echo "$str" >>tmpsedcommand.sed
    done 
} 

#===  FUNCTION  ================================================================
#          NAME:  read_filename()
#   DESCRIPTION: 循环读入每一行文件名进行替换 
#===============================================================================
read_filename() {
    filepath=`pwd`
    while read soufile desfile; do
        case "${soufile:0:3}" in
            "###")
                s=${soufile#*\#\#\#.*}
                s="$filepath${s//\\/}"
                d=${desfile//\\/}
                echo "make ln $s -> $d" 
                if [ -f "$d" ]; then
                    rm  $d
                fi
                ln -sf $s $d
                ;;
            "#S#")
                s=${soufile#*\#S\#\.*}
                s=${s//\\/}
                d=${desfile//\\/}
                echo "root make ln $s -> $d" 
                if [ -f "$d" ]; then
                    sudo rm  $d
                fi
                sudo ln -sf $s $d
                ;;
            *)
                s=`echo "$soufile" | sed -e 's/\\\\\//\//g'`
                d=`echo "$desfile" | sed -e 's/\\\\\//\//g'`
                echo "正在转换文件: $s -> ${d}"
                sed -f tmpsedcommand.sed "$s" > "${d}"
            ;;
        esac
    done
}

#-------------------------------------------------------------------------------
#   main 部分
#-------------------------------------------------------------------------------

cd "$(dirname "$0")"

#清空临时命令文件
cat /dev/null >  tmpsedcommand.sed

#清除注释、空行、替换/符号为\/
# 生成sed 命令文件
sed -e '/^\s*--/d' -e '/^\s*$/d' secret.txt -e 's/\//\\\\\//g'| read_replace_var 
# 生成中间文件列表,替换文件列表中的敏感字段
sed -e '/^\s*--/d' -e '/^\s*$/d' -f tmpsedcommand.sed file.list > tmpfilelist

# 逐个读入文件
sed  -e 's/\//\\\\\//g' tmpfilelist | read_filename

xmonad --recompile  && xmonad --restart
rm tmpsedcommand.sed
rm tmpfilelist

